"""Update bot_instance parameters to use MutableDict for change tracking

Revision ID: 2084380c17ef
Revises: 6f6e5a3115e1
Create Date: 2025-06-05 20:10:16.144504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2084380c17ef'
down_revision: Union[str, None] = '6f6e5a3115e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
