"""Remove account_id from brokerage_connections

Revision ID: 5d84b2a6d73e
Revises: 
Create Date: 2025-06-15 21:17:33.082623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added import for sqlmodel
from datetime import datetime # Added import for datetime


# revision identifiers, used by Alembic.
revision: str = '5d84b2a6d73e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brokerage_connections', schema=None) as batch_op:
        batch_op.drop_column('account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brokerage_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.String(), nullable=False))
    # ### end Alembic commands ###
