"""Rename broker_name to brokerage_name and add expires_at to BrokerageConnection

Revision ID: 6f6e5a3115e1
Revises: 543c79797661
Create Date: 2025-06-05 01:09:03.145009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6e5a3115e1'
down_revision: Union[str, None] = '543c79797661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brokerage_connections') as batch_op:
        batch_op.add_column(sa.Column('brokerage_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('api_key', existing_type=sa.BLOB(), nullable=True)

    # Populate the new 'brokerage_name' column with a default value for existing rows
    # Assuming a default value like 'Unknown' or migrating from the old 'broker_name'
    # Since we are renaming, we should copy the data from the old column before dropping it.
    op.execute("UPDATE brokerage_connections SET brokerage_name = broker_name")

    with op.batch_alter_table('brokerage_connections') as batch_op:
        batch_op.alter_column('brokerage_name', existing_type=sa.String(length=50), nullable=False)
        batch_op.drop_column('broker_name')

    with op.batch_alter_table('sessions') as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions') as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=True, autoincrement=True)

    with op.batch_alter_table('brokerage_connections') as batch_op:
        batch_op.add_column(sa.Column('broker_name', sa.VARCHAR(length=50), nullable=False))
        # Copy data back if needed, or set a default
        op.execute("UPDATE brokerage_connections SET broker_name = brokerage_name")
        batch_op.alter_column('api_key', existing_type=sa.BLOB(), nullable=False)
        batch_op.drop_column('expires_at')
        batch_op.drop_column('brokerage_name')
    # ### end Alembic commands ###
