"""Make strategy parameters generic

Revision ID: 7c86ffd50dd3
Revises: bf3c034e73b7
Create Date: 2025-06-04 23:02:58.176957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c86ffd50dd3'
down_revision: Union[str, None] = 'bf3c034e73b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_definition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_definition_id'], ['strategy_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_parameters_id'), 'strategy_parameters', ['id'], unique=False)
    op.drop_index(op.f('ix_strategy_parameters_pmcc_id'), table_name='strategy_parameters_pmcc')
    op.drop_table('strategy_parameters_pmcc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_parameters_pmcc',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_definition_id', sa.INTEGER(), nullable=False),
    sa.Column('delta_threshold', sa.FLOAT(), nullable=False),
    sa.Column('days_to_expiration_long', sa.INTEGER(), nullable=False),
    sa.Column('days_to_expiration_short', sa.INTEGER(), nullable=False),
    sa.Column('profit_target_percentage', sa.FLOAT(), nullable=False),
    sa.Column('stop_loss_percentage', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_definition_id'], ['strategy_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_parameters_pmcc_id'), 'strategy_parameters_pmcc', ['id'], unique=False)
    op.drop_index(op.f('ix_strategy_parameters_id'), table_name='strategy_parameters')
    op.drop_table('strategy_parameters')
    # ### end Alembic commands ###
