"""Add parameters column to bot_instances table

Revision ID: 80133e85bc48
Revises: 7c86ffd50dd3
Create Date: 2025-06-05 01:00:58.355729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80133e85bc48'
down_revision: Union[str, None] = '7c86ffd50dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_instances', sa.Column('parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_instances', 'parameters')
    # ### end Alembic commands ###
