"""Remove MarketDataCache_OptionChain model

Revision ID: 9de27f1e4f49
Revises: 024f522d9030
Create Date: 2025-06-08 19:18:04.885403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de27f1e4f49'
down_revision: Union[str, None] = '024f522d9030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_symbol_expiration'), table_name='market_data_cache_option_chain')
    op.drop_table('market_data_cache_option_chain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_cache_option_chain',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('expiration_date', sa.DATETIME(), nullable=True),
    sa.Column('strike_price', sa.FLOAT(), nullable=False),
    sa.Column('option_type', sa.VARCHAR(), nullable=False),
    sa.Column('bid', sa.FLOAT(), nullable=True),
    sa.Column('ask', sa.FLOAT(), nullable=True),
    sa.Column('implied_volatility', sa.FLOAT(), nullable=True),
    sa.Column('delta', sa.FLOAT(), nullable=True),
    sa.Column('gamma', sa.FLOAT(), nullable=True),
    sa.Column('theta', sa.FLOAT(), nullable=True),
    sa.Column('vega', sa.FLOAT(), nullable=True),
    sa.Column('open_interest', sa.INTEGER(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_symbol_expiration'), 'market_data_cache_option_chain', ['symbol', 'expiration_date'], unique=False)
    # ### end Alembic commands ###
